package org.opensims.db.om;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Mon Aug 09 19:10:11 EDT 2004]
 *
 *  You should add additional methods to this class to meet the
 *  application requirements.  This class will only be generated as
 *  long as it does not already exist in the output directory.
 */
public class AlertDefPeer
    extends org.opensims.db.om.BaseAlertDefPeer
{
}
