package org.opensims.db.om;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Fri Nov 11 14:00:11 CST 2005]
 *
 *  You should add additional methods to this class to meet the
 *  application requirements.  This class will only be generated as
 *  long as it does not already exist in the output directory.
 */
 
public class HostOrgLinkPeer
    extends org.opensims.db.om.BaseHostOrgLinkPeer
{
}
