package org.opensims.db.om;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Fri Aug 06 09:03:47 CDT 2004]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */

public class
    HostPeer
    extends org.opensims.db.om.BaseHostPeer
{
    public static java.util.List
	doSelectAll ()
	throws Exception
    {
	org.apache.torque.util.Criteria crit = new org.apache.torque.util.Criteria();

	return doSelect(crit);
    }
}
