package org.opensims.db.om;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Thu Nov 10 23:37:26 CST 2005]
 *
 *  You should add additional methods to this class to meet the
 *  application requirements.  This class will only be generated as
 *  long as it does not already exist in the output directory.
 */
public class OrgPeer
    extends org.opensims.db.om.BaseOrgPeer
{
}
