
package org.opensims.db.om;


import org.apache.torque.om.Persistent;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Mon Oct 04 14:04:31 CDT 2004]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */
public  class Response
    extends org.opensims.db.om.BaseResponse
    implements Persistent
{
}
