#!/usr/bin/perl

print 'xl0:	flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> mtu 1500
        options=b<RXCSUM,TXCSUM,VLAN_MTU>
        inet 172.16.1.8 netmask 0xffffff00 broadcast 172.16.1.255
        inet6 fe80::210:4bff:fe72:666a%xl0 prefixlen 64 scopeid 0x1 
        ether 00:10:4b:72:66:6a
        media: Ethernet autoselect (100baseTX <full-duplex>)
        status: active
plip0:	flags=8810<POINTOPOINT,SIMPLEX,MULTICAST> mtu 1500
lo0:	flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> mtu 16384
        inet 127.0.0.1 netmask 0xff000000 
        inet6 ::1 prefixlen 128 
        inet6 fe80::1%lo0 prefixlen 64 scopeid 0x3 

';
