/**
 * @LICENSE@
 */

package org.opensims.model;

/**
 * $CVSId: AutoDiscovery.java,v 1.2 2004/09/15 20:50:49 paco Exp $
 * $Id: AutoDiscovery.java 1 2008-01-10 18:37:05Z smoot $
 * <P>This file has been automatically generated by UML tools in OpenSIMS</P>
 */

public interface
    AutoDiscovery
{

    public boolean
	loadModelFile (String param);

    public boolean
	saveModelFile (String param);

    public boolean
	updateHostAssignments (String param);

    public boolean
	transmitToRepository (String param);

    public boolean
	setCorrelationEnable (String param);

    public boolean
	networkAllows (String param);

    public boolean
	configPlugin (String param);

    public boolean
	setReceipt (String param);

    public boolean
	waitKnownReceipts (String param);
}
